#ifndef WEVENT_GLOBAL_H
#define WEVENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEVENT_LIBRARY)
#  define WEVENTSHARED_EXPORT Q_DECL_EXPORT
#  define WMESSAGESHARED_EXPORT Q_DECL_EXPORT
#  define WSETIDSHARED_EXPORT Q_DECL_EXPORT
#  define WNICKREQUESTSHARED_EXPORT Q_DECL_EXPORT
#  define WNICKRESPONSESHARED_EXPORT Q_DECL_EXPORT
#  define WCLIENTLIST_EXPORT Q_DECL_EXPORT
#else
#  define WEVENTSHARED_EXPORT Q_DECL_IMPORT
#  define WMESSAGESHARED_EXPORT Q_DECL_IMPORT
#  define WSETIDSHARED_EXPORT Q_DECL_IMPORT
#  define WNICKREQUESTSHARED_EXPORT Q_DECL_IMPORT
#  define WNICKRESPONSESHARED_EXPORT Q_DECL_IMPORT
#  define WCLIENTLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // WEVENT_GLOBAL_H
